  ingress:
    # Enable ingress record generation
    enabled: false
    # Ingress path type
    pathType: ImplementationSpecific
    ingressClassName: ""
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: HTTPS
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    # Ingress TLS configuration
    tls: []
      # - secretName: tls-vcluster.local
      #   hosts:
      #     - vcluster.local

  vcluster:
    storage:
      size: 1Gi

    # Syncer configuration
    syncer:
      extraArgs:
        - --tls-san=vcluster-k0s.argocd.kind.example.com

    ## Configure SecurityContext of the containers in the VCluster pod
    #securityContext:
    #  runAsUser: 12345
    #  runAsGroup: 12345
    #  runAsNonRoot: true
#
    ## Configure fsGroup
    ## The field is specified, all processes of the container are also part of the supplementary group ID 12345
    #fsGroup: 12345

  init:
    helm:
    - chart:
        name: cert-manager
        repo: https://charts.jetstack.io
      # optional field
      values: |-
        replicaCount: 1
        installCRDs: true

      release:
        name: cert-manager
        namespace: kube-system
      
    - chart:
        name: ingress-nginx
        repo: https://kubernetes.github.io/ingress-nginx
      # optional field
      values: |-
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app.kubernetes.io/component
                    operator: In
                    values:
                    - controller
                topologyKey: topology.kubernetes.io/zone
              weight: 100
        controller:
          containerPort:
            http: 3008
            https: 3044
          extraArgs:
            http-port: 3008
            https-port: 3044
          hostNetwork: false
          image:
            allowPrivilegeEscalation: false
          ingressClassResource:
            controllerValue: k8s.io/ingress-nginx
            default: true
            enabled: true
            name: vcluster-nginx
          metrics:
            enabled: true
            service:
              annotations:
                prometheus.io/port: "10254"
                prometheus.io/scrape: "true"
          replicaCount: 2
          service:
            annotations:
              external-dns.alpha.kubernetes.io/hostname: sample-app.{{ .Values.ingress.host }}
            enabled: true
            type: LoadBalancer
          config:
            use-proxy-protocol: "false"
        nameOverride: custom
      release:
        name: ingress-nginx
        namespace: ingress-nginx


    