apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: vcluster-application-set
  namespace: argocd
spec:
  generators:
  - matrix:
      generators:
      - git:
          repoURL: https://github.com/manherna/test-vcluster-gitops.git
          revision: HEAD
          directories:
            - path: application-sets/charts/*
      - list:
          elements:
          - namespace: team-a
          - namespace: team-b
          - namespace: team-c
  template:      
    metadata:
      name: '{{path.basename}}-{{namespace}}'
    spec:
      # The project the application belongs to.
      project: default
      # Source of the application manifests
      source:
        repoURL: https://github.com/manherna/test-vcluster-gitops.git
        targetRevision: HEAD
        path: '{{path}}'
      
      # Destination cluster and namespace to deploy the application
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'

      # Sync policy
      syncPolicy:
        syncOptions:
          - CreateNamespace=true  
        automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
          prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
          selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
      