apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: vcluster-application-set
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - matrix:
      generators:
        - pullRequest:
            github:
              # The GitHub organization or user.
              owner: manherna
              # The Github repository
              repo: test-vcluster-gitops
            requeueAfterSeconds: 20
        - list:
           elements:
             - vclusterName: test-vcluster
  - matrix:
      generators:
        - pullRequest:
            github:
              # The GitHub organization or user.
              owner: manherna
              # The Github repository
              repo: test-vcluster-gitops
            requeueAfterSeconds: 20
        - list:
           elements:
             - vclusterName: tost-vcluster

  template:
    metadata:
      name: 'vc-{{.vclusterName}}-{{.number}}'
    annotations:
      example.com/my-annotation: '{{ print . }}'
    spec:
      # The project the application belongs to.
      project: default
      # Source of the application manifests
      source:
        repoURL: https://github.com/manherna/test-vcluster-gitops.git
        targetRevision: 'HEAD'
        path: ./charts/vcluster
        helm:
          parameters:
            - name: "vcluster.syncer.extraArgs[0]"
              value: "--tls-san={{.vclusterName}}-{{.number}}.argocd.kind.example.com"
            - name: ingress.clusterIssuer
              value: letsencrypt-dns
            - name: ingress.host
              value: "{{.vclusterName}}-{{.number}}.argocd.kind.example.com"
      # Destination cluster and namespace to deploy the application
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{.vclusterName}}-{{.number}}"

      # Sync policy
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
          prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
          selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
